# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8b549ee3fc6cce43d1200452de0b037e2fa0b697cca554cdaeb00b7e24fe5a3869d2faf147a8009431becdc6b2e96b6f88578ae8c2b7f4a69c2bc095c9e35ac

test:
  secret_key_base: 17c00f8e5c5869ea2e192797a04ae9ed1288a4736aba674047f7f4667ef2db02113c7c6db758134980f645d9f8f15b2909c29e50bc77baf0731dd6f760a14642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
